### PR TITLE
GeCraft - OBS support

### PR DESCRIPTION
**Pull request by foxprogs**
## Added support for OBS, saving the filter after installing a new list of books, minor changes

- [ ]

## Test Instructions

- [ ]
TODO @ancientTexts-net

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
@foxprogs - My apologies, but you will have to resolve some conflicts here. We just released a new version of the bible-reference-rcl to add an optional callback before we change a reference.  This will allow the app to warn the user if they have unsaved changes before they navigate to a different verse.

**Comment by foxprogs** [comment]
@PhotoNomad0 Thanks, I fixed it.

**Comment by PhotoNomad0** [comment]
@foxprogs Status update: I published your PR changes bible-reference-rcl as `1.1.0-alpha` so we can test with gateway edit.  So far is looking good.  

Also I recommend updating version in package.json to `1.1.0`

**Comment by foxprogs** [comment]
@PhotoNomad0 we tested version `1.1.0-alpha` in BSA, it works well.

**Comment by PhotoNomad0** [comment]
@foxprogs - merged and published as version 1.1.0.  Thanks for the help!

**Pull request merged**
